apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnr-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rnr-frontend
  template:
    metadata:
      labels:
        app: rnr-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend-container
        image: mrmonster786/employee-rr-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=400"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rnr-frontend
spec:
  type: NodePort
  selector:
    app: rnr-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000